# Generated by Django 3.2.12 on 2022-02-03 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='img',
            field=models.ImageField(default='abcdef', upload_to='photos'),
            preserve_default=False,
        ),
    ]
