# Generated by Django 3.2.10 on 2022-01-28 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newschoolapp', '0002_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='desc',
            new_name='descriptn',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='img',
            new_name='image',
        ),
    ]
